-- Normalized Lookup Tables
INSERT INTO countries (name) VALUES 
('Japan'), ('France'), ('Italy'), ('Spain'), ('USA'),
('Morocco'), ('Thailand'), ('Iceland'), ('Cambodia');

INSERT INTO kb_categories (name) VALUES 
('etiquette'), ('laws'), ('safety'), ('culture'), ('transport'),
('food'), ('timing'), ('weather'), ('other');

-- Destinations
INSERT INTO destinations (slug, name, country_id, description, image_url, best_time, occasions, language_tips) VALUES
('kyoto', 'Kyoto', (SELECT id FROM countries WHERE name='Japan'), 'Historic temples, gardens and traditional culture.', '/images/kyoto.png', 'Oct–Nov (Autumn)', 'Gion Matsuri Festival', 'Hello = Konnichiwa'),
('tokyo', 'Tokyo', (SELECT id FROM countries WHERE name='Japan'), 'Modern city with tradition, technology and great food.', '/images/tokyo.png', 'March–April', 'Cherry Blossom Season', 'Thank you = Arigato'),
('paris', 'Paris', (SELECT id FROM countries WHERE name='France'), 'Museums, cafés and iconic landmarks.', '/images/paris.png', 'May–Sept', 'Bastille Day (July 14)', 'Please = S''il vous plaît'),
('rome', 'Rome', (SELECT id FROM countries WHERE name='Italy'), 'Ancient history, architecture and culture.', '/images/rome.png', 'Sept–Oct', 'Easter Celebrations', 'Excuse me = Mi scusi'),
('barcelona', 'Barcelona', (SELECT id FROM countries WHERE name='Spain'), 'Beaches, art and architecture.', '/images/barcelona.png', 'May–June', 'Primavera Sound Festival', 'The bill = La cuenta'),
('newyork', 'New York', (SELECT id FROM countries WHERE name='USA'), 'City life, entertainment and famous sights.', '/images/newyork.png', 'Sept–Nov', 'New Year''s Eve Ball Drop', 'Tip 20% at restaurants'),
('marrakech', 'Marrakech', (SELECT id FROM countries WHERE name='Morocco'), 'Markets, culture, and local experiences.', '/images/marrakech.png', 'March–May', 'International Film Festival', 'Thank you = Shokran'),
('bangkok', 'Bangkok', (SELECT id FROM countries WHERE name='Thailand'), 'Street food, temples and nightlife.', '/images/bangkok.png', 'Nov–Feb', 'Songkran (Water Festival)', 'Hello = Sawasdee'),
('reykjavik', 'Reykjavik', (SELECT id FROM countries WHERE name='Iceland'), 'Nature, northern lights and unique landscapes.', '/images/reykjavik.png', 'Sept–March', 'Iceland Airwaves', 'Cheers = Skál!'),
('siemreap', 'Siem Reap', (SELECT id FROM countries WHERE name='Cambodia'), 'Gateway to the ancient ruins of Angkor Wat.', '/images/siemreap.png', 'Dec–Feb', 'Khmer New Year (April)', 'Hello = Susadei');

-- Accommodations

-- KYOTO
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Traditional Ryokan Stay', 120.00, 4.7 FROM destinations WHERE slug='kyoto';
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Gion Guest House', 65.00, 4.2 FROM destinations WHERE slug='kyoto';
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Higashiyama Boutique Inn', 95.00, 4.5 FROM destinations WHERE slug='kyoto';
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Kyoto Budget Hostel', 30.00, 3.9 FROM destinations WHERE slug='kyoto';

-- TOKYO
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Shinjuku Sky Hotel', 110.00, 4.5 FROM destinations WHERE slug='tokyo';
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Capsule Inn Tokyo', 45.00, 4.0 FROM destinations WHERE slug='tokyo';
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Shibuya Luxury Suites', 175.00, 4.8 FROM destinations WHERE slug='tokyo';
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Asakusa Heritage Hotel', 80.00, 4.3 FROM destinations WHERE slug='tokyo';

-- PARIS
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Boutique Marais Hotel', 155.00, 4.6 FROM destinations WHERE slug='paris';
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Montmartre Artist Loft', 90.00, 4.3 FROM destinations WHERE slug='paris';
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Seine View Apartment', 200.00, 4.9 FROM destinations WHERE slug='paris';
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Latin Quarter Budget Room', 55.00, 3.8 FROM destinations WHERE slug='paris';

-- ROME
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Colosseum View Apartment', 130.00, 4.8 FROM destinations WHERE slug='rome';
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Trastevere Guesthouse', 75.00, 4.4 FROM destinations WHERE slug='rome';
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Vatican District Hotel', 110.00, 4.5 FROM destinations WHERE slug='rome';
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Roman Backpacker Hostel', 28.00, 3.7 FROM destinations WHERE slug='rome';

-- BARCELONA
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Las Ramblas Suites', 95.00, 4.3 FROM destinations WHERE slug='barcelona';
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Gothic Quarter Apartment', 70.00, 4.2 FROM destinations WHERE slug='barcelona';
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Barceloneta Beach Hotel', 140.00, 4.6 FROM destinations WHERE slug='barcelona';
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Eixample Budget Hostel', 35.00, 3.9 FROM destinations WHERE slug='barcelona';

-- NEW YORK
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Manhattan Loft Hotel', 210.00, 4.4 FROM destinations WHERE slug='newyork';
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Brooklyn Boutique Stay', 130.00, 4.5 FROM destinations WHERE slug='newyork';
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Midtown Business Hotel', 185.00, 4.2 FROM destinations WHERE slug='newyork';
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Harlem Cultural Hostel', 60.00, 4.0 FROM destinations WHERE slug='newyork';

-- MARRAKECH
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Riad Dream Oasis', 80.00, 4.9 FROM destinations WHERE slug='marrakech';
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Medina Heritage Riad', 65.00, 4.6 FROM destinations WHERE slug='marrakech';
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Palmeraie Luxury Resort', 180.00, 4.8 FROM destinations WHERE slug='marrakech';
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Jemaa el-Fna Budget Inn', 25.00, 3.8 FROM destinations WHERE slug='marrakech';

-- BANGKOK
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Riverside Luxury Resort', 140.00, 4.7 FROM destinations WHERE slug='bangkok';
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Sukhumvit Serviced Apartment', 85.00, 4.3 FROM destinations WHERE slug='bangkok';
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Old Town Heritage Hotel', 60.00, 4.4 FROM destinations WHERE slug='bangkok';
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Khao San Road Hostel', 18.00, 3.6 FROM destinations WHERE slug='bangkok';

-- REYKJAVIK
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Northern Lights Cabin', 180.00, 4.6 FROM destinations WHERE slug='reykjavik';
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Downtown Reykjavik Hotel', 130.00, 4.4 FROM destinations WHERE slug='reykjavik';
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Golden Circle Guesthouse', 95.00, 4.5 FROM destinations WHERE slug='reykjavik';
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Laugavegur Budget Hostel', 45.00, 4.0 FROM destinations WHERE slug='reykjavik';

-- SIEM REAP
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Angkor Heritage Villa', 75.00, 4.9 FROM destinations WHERE slug='siemreap';
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Temple View Hostel', 25.00, 4.1 FROM destinations WHERE slug='siemreap';
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Pub Street Boutique Hotel', 55.00, 4.3 FROM destinations WHERE slug='siemreap';
INSERT INTO accommodations (destination_id, title, price_per_night, rating)
SELECT id, 'Angkor Riverside Resort', 110.00, 4.7 FROM destinations WHERE slug='siemreap';



-- KNOWLEDGE BASE

-- KYOTO
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='kyoto'), (SELECT id FROM kb_categories WHERE name='etiquette'), 'Temple Behaviour', 'Speak quietly in temple grounds and avoid blocking pathways when taking photos.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='kyoto'), (SELECT id FROM kb_categories WHERE name='etiquette'), 'Shoe Removal', 'Remove your shoes before entering traditional spaces such as ryokan rooms, tatami areas, and some shrines.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='kyoto'), (SELECT id FROM kb_categories WHERE name='etiquette'), 'Maiko and Geiko Respect', 'Do not chase, block, or touch maiko or geiko in Gion. They are working professionals and unsolicited contact is considered disrespectful.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='kyoto'), (SELECT id FROM kb_categories WHERE name='laws'), 'Private Property Respect', 'Do not enter private alleyways, homes, or geisha districts marked as restricted to visitors.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='kyoto'), (SELECT id FROM kb_categories WHERE name='laws'), 'Drone Restrictions', 'Flying drones over temple grounds and historic districts is prohibited without a permit.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='kyoto'), (SELECT id FROM kb_categories WHERE name='laws'), 'Littering Fines', 'Littering in public spaces can result in fines. Always use designated bins or carry rubbish with you.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='kyoto'), (SELECT id FROM kb_categories WHERE name='safety'), 'Bicycle Safety', 'Cycling is popular in Kyoto but use designated lanes and lock your bike securely. Riding on pavements where prohibited can result in warnings.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='kyoto'), (SELECT id FROM kb_categories WHERE name='safety'), 'Emergency Numbers', 'Police in Japan can be reached on 110. Ambulance and fire services are on 119. Operators may have limited English so keep your address written in Japanese.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='kyoto'), (SELECT id FROM kb_categories WHERE name='culture'), 'Quiet Public Spaces', 'Noise levels are kept low on public transport and in traditional streets, especially early morning and evening.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='kyoto'), (SELECT id FROM kb_categories WHERE name='culture'), 'Seasonal Festivals', 'The Gion Matsuri in July and autumn leaf season in November attract large crowds. Book accommodation months in advance.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='kyoto'), (SELECT id FROM kb_categories WHERE name='culture'), 'Tea Ceremony Etiquette', 'If attending a tea ceremony, follow the host''s lead, avoid unnecessary talking, and handle utensils with care.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='kyoto'), (SELECT id FROM kb_categories WHERE name='transport'), 'IC Card Travel', 'Get a Suica or Pasmo card for seamless bus and train travel across the city.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='kyoto'), (SELECT id FROM kb_categories WHERE name='transport'), 'Bus Routes', 'City buses are the most convenient way to reach many temples. Buy a day pass for unlimited travel on most routes.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='kyoto'), (SELECT id FROM kb_categories WHERE name='transport'), 'Taxi Etiquette', 'Taxis in Kyoto are metered and reliable. The doors open and close automatically so do not touch them.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='kyoto'), (SELECT id FROM kb_categories WHERE name='food'), 'Kaiseki Dining', 'Kyoto is famous for kaiseki, a traditional multi-course meal. Reservations are essential at top restaurants and smart dress is expected.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='kyoto'), (SELECT id FROM kb_categories WHERE name='food'), 'Eating While Walking', 'Eating while walking in temple and market areas is generally considered impolite. Eat at designated spots or while standing near the stall.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='kyoto'), (SELECT id FROM kb_categories WHERE name='food'), 'Vegetarian Options', 'Shojin ryori is traditional Buddhist vegetarian cuisine and is widely available near temple areas.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='kyoto'), (SELECT id FROM kb_categories WHERE name='timing'), 'Autumn Crowds', 'October and November are the busiest months due to autumn foliage. Arrive at popular temples before 8am to avoid large crowds.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='kyoto'), (SELECT id FROM kb_categories WHERE name='timing'), 'Cherry Blossom Season', 'Late March to early April brings cherry blossoms to parks and temple gardens. Crowds peak during this period.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='kyoto'), (SELECT id FROM kb_categories WHERE name='weather'), 'Summer Heat', 'July and August are hot and humid. Carry water, wear light clothing, and plan outdoor visits for early morning or evening.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='kyoto'), (SELECT id FROM kb_categories WHERE name='weather'), 'Rainy Season', 'June is the rainy season in Kyoto. Pack a compact umbrella and allow extra time for outdoor sightseeing.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='kyoto'), (SELECT id FROM kb_categories WHERE name='other'), 'Photography in Gion', 'Avoid obstructing narrow streets or photographing people too closely in historic districts. Some areas now prohibit photography on private alleys.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='kyoto'), (SELECT id FROM kb_categories WHERE name='other'), 'Tipping Culture', 'Tipping is not customary in Japan and can sometimes cause offence. Express gratitude verbally instead.';


-- TOKYO
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='tokyo'), (SELECT id FROM kb_categories WHERE name='etiquette'), 'Train Manners', 'Keep phone calls silent on trains, give up priority seats, and avoid eating on local services.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='tokyo'), (SELECT id FROM kb_categories WHERE name='etiquette'), 'Queuing', 'Always queue in an orderly line at train platforms and popular attractions. Pushing in is considered very rude.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='tokyo'), (SELECT id FROM kb_categories WHERE name='etiquette'), 'Tattoo Awareness', 'Many public baths and some gyms prohibit tattooed visitors. Check policies in advance if you have visible tattoos.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='tokyo'), (SELECT id FROM kb_categories WHERE name='laws'), 'Alcohol in Public', 'Drinking alcohol in parks and public spaces is legal but behaving disruptively can attract police attention.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='tokyo'), (SELECT id FROM kb_categories WHERE name='laws'), 'Drug Laws', 'Japan has extremely strict drug laws. Even prescription medications common elsewhere may be restricted. Check before travelling.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='tokyo'), (SELECT id FROM kb_categories WHERE name='laws'), 'ID Requirements', 'Carry your passport or a copy at all times. Police can request identification and you are legally required to comply.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='tokyo'), (SELECT id FROM kb_categories WHERE name='safety'), 'Late Night Navigation', 'Tokyo is very safe at night but confirm the last train time before staying out late as services stop around midnight.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='tokyo'), (SELECT id FROM kb_categories WHERE name='safety'), 'Earthquake Preparedness', 'Tokyo experiences minor earthquakes regularly. Familiarise yourself with your accommodation''s evacuation procedure on arrival.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='tokyo'), (SELECT id FROM kb_categories WHERE name='culture'), 'Vending Machine Culture', 'Hot and cold drinks, snacks, and even full meals are available from vending machines on almost every street.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='tokyo'), (SELECT id FROM kb_categories WHERE name='culture'), 'Capsule Hotels', 'Capsule hotels are a unique Tokyo experience offering compact sleeping pods. They are clean, efficient, and popular with solo travellers.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='tokyo'), (SELECT id FROM kb_categories WHERE name='culture'), 'Hanami Tradition', 'Cherry blossom viewing, known as hanami, involves picnics under blossoming trees. It is a cherished seasonal tradition.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='tokyo'), (SELECT id FROM kb_categories WHERE name='transport'), 'Rush Hour Trains', 'Avoid travelling on trains during peak commuting hours if carrying large luggage as services become extremely crowded.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='tokyo'), (SELECT id FROM kb_categories WHERE name='transport'), 'IC Card', 'A Suica or Pasmo IC card works on all trains, buses, and even in many convenience stores across Tokyo.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='tokyo'), (SELECT id FROM kb_categories WHERE name='transport'), 'Airport Express', 'The Narita Express and Limousine Bus connect major airports to the city. Book tickets in advance during busy seasons.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='tokyo'), (SELECT id FROM kb_categories WHERE name='food'), 'Ramen Etiquette', 'Slurping noodles is acceptable and considered a sign of enjoyment. Many ramen shops have solo counter seating.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='tokyo'), (SELECT id FROM kb_categories WHERE name='food'), 'Conveyor Belt Sushi', 'Kaiten-zushi restaurants use colour-coded plates to indicate price. Take only what you will eat to avoid waste.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='tokyo'), (SELECT id FROM kb_categories WHERE name='food'), 'No Tipping', 'Tipping is not expected or practised in Japan. Exceptional service is standard and does not require additional payment.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='tokyo'), (SELECT id FROM kb_categories WHERE name='timing'), 'Attraction Timing', 'Visit popular sites like Senso-ji temple early in the morning on weekdays to avoid the largest crowds.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='tokyo'), (SELECT id FROM kb_categories WHERE name='timing'), 'Golden Week', 'Golden Week in late April to early May is a national holiday period when attractions, transport, and hotels are extremely busy.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='tokyo'), (SELECT id FROM kb_categories WHERE name='weather'), 'Summer Humidity', 'June to August is very hot and humid. Stay hydrated, use sunscreen, and take breaks in air-conditioned spaces.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='tokyo'), (SELECT id FROM kb_categories WHERE name='weather'), 'Typhoon Season', 'Typhoons can occur between August and October. Monitor weather updates and follow local guidance if one approaches.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='tokyo'), (SELECT id FROM kb_categories WHERE name='other'), 'Cash Culture', 'Many smaller restaurants and shops are cash only. Always carry some yen as card payments are not universally accepted.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='tokyo'), (SELECT id FROM kb_categories WHERE name='other'), 'Rubbish Bins', 'Public bins are rare in Tokyo. Carry a small bag for your rubbish and dispose of it at convenience stores or your accommodation.';


-- PARIS
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='paris'), (SELECT id FROM kb_categories WHERE name='etiquette'), 'Greeting Customs', 'Say Bonjour when entering any shop, café, or business. Failing to greet staff is considered impolite.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='paris'), (SELECT id FROM kb_categories WHERE name='etiquette'), 'Dress Standards', 'Parisians generally dress smartly. While casual clothing is acceptable for tourists, overly casual attire may attract attention in upscale restaurants.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='paris'), (SELECT id FROM kb_categories WHERE name='etiquette'), 'Noise in Residential Areas', 'Keep noise levels low in residential streets and avoid loud behaviour late at night out of respect for locals.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='paris'), (SELECT id FROM kb_categories WHERE name='laws'), 'Ticket Validation', 'Always validate Metro and bus tickets before travel. Inspections occur regularly and fines for invalid tickets are immediate.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='paris'), (SELECT id FROM kb_categories WHERE name='laws'), 'Photography of Officials', 'Photographing police officers or military personnel is restricted and can lead to questioning.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='paris'), (SELECT id FROM kb_categories WHERE name='laws'), 'Eiffel Tower at Night', 'The illuminated Eiffel Tower is copyrighted. Sharing commercial photos of the lit tower without permission may violate copyright law.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='paris'), (SELECT id FROM kb_categories WHERE name='safety'), 'Pickpocket Hotspots', 'Be especially alert around the Eiffel Tower, Sacré-Cœur, and on Metro Line 1. Keep bags closed and in front of you.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='paris'), (SELECT id FROM kb_categories WHERE name='safety'), 'Petition Scams', 'Be wary of strangers approaching you with clipboards and petitions near tourist sites. This is a common distraction theft method.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='paris'), (SELECT id FROM kb_categories WHERE name='safety'), 'Emergency Number', 'The emergency number in France is 112 for all services. Police can also be reached on 17.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='paris'), (SELECT id FROM kb_categories WHERE name='culture'), 'Café Sitting Time', 'In Paris it is perfectly acceptable to sit at a café table for hours after finishing your drink. There is no rush to leave.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='paris'), (SELECT id FROM kb_categories WHERE name='culture'), 'Museum Culture', 'Paris has world-class museums. The Louvre and Musée d''Orsay require timed entry tickets booked online to avoid long queues.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='paris'), (SELECT id FROM kb_categories WHERE name='culture'), 'Bastille Day', 'July 14 is France''s national holiday with fireworks, military parades, and street celebrations. Transport and sites can be very busy.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='paris'), (SELECT id FROM kb_categories WHERE name='transport'), 'Metro System', 'The Paris Metro is fast and extensive. Buy a carnet of ten tickets for better value than single tickets.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='paris'), (SELECT id FROM kb_categories WHERE name='transport'), 'RER Trains', 'RER trains connect central Paris to the airports and Versailles. Validate your ticket before boarding and keep it until exit.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='paris'), (SELECT id FROM kb_categories WHERE name='transport'), 'Cycling', 'Vélib bike-share stations are across the city. Cycle lanes are expanding but traffic can be fast in central areas.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='paris'), (SELECT id FROM kb_categories WHERE name='food'), 'Café Culture', 'Table service is standard. Catching a waiter''s eye politely is the norm. Service charge is usually included in the bill.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='paris'), (SELECT id FROM kb_categories WHERE name='food'), 'Boulangerie Etiquette', 'Greet the baker when entering and ask for items individually rather than pointing. Fresh baguettes are sold throughout the day.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='paris'), (SELECT id FROM kb_categories WHERE name='food'), 'Water at Restaurants', 'Asking for une carafe d''eau provides free tap water which is safe to drink and perfectly acceptable to request.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='paris'), (SELECT id FROM kb_categories WHERE name='timing'), 'August Closures', 'Many Parisian businesses and smaller restaurants close in August when locals take their own holidays. Plan around this.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='paris'), (SELECT id FROM kb_categories WHERE name='timing'), 'Museum Queue Times', 'Arrive at major museums when they open to avoid the longest queues. Online tickets with timed entry slots save significant time.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='paris'), (SELECT id FROM kb_categories WHERE name='weather'), 'Spring Showers', 'Spring is pleasant but expect rain. A compact umbrella is useful throughout March to May.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='paris'), (SELECT id FROM kb_categories WHERE name='weather'), 'Winter Cold', 'December to February can be cold and grey. Many outdoor attractions are quieter but dress in warm layers.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='paris'), (SELECT id FROM kb_categories WHERE name='other'), 'Photography Courtesy', 'Be considerate when photographing people in cafés, markets, and residential streets. Always ask permission for close-up portraits.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='paris'), (SELECT id FROM kb_categories WHERE name='other'), 'Language Effort', 'Making an effort to speak basic French, even just Bonjour and Merci, is appreciated and often results in a warmer response from locals.';


-- ROME
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='rome'), (SELECT id FROM kb_categories WHERE name='etiquette'), 'Church Dress Code', 'Cover shoulders and knees when entering churches. Guards at St Peter''s Basilica enforce this strictly.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='rome'), (SELECT id FROM kb_categories WHERE name='etiquette'), 'Greeting Style', 'Italians often greet with two kisses on the cheek among friends. A handshake is appropriate in formal or first-time meetings.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='rome'), (SELECT id FROM kb_categories WHERE name='etiquette'), 'Dining Pace', 'Meals in Rome are leisurely social occasions. Rushing a waiter or asking for the bill too early can come across as impolite.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='rome'), (SELECT id FROM kb_categories WHERE name='laws'), 'Heritage Site Rules', 'Do not climb on monuments, sit on the Spanish Steps, or throw coins in the Trevi Fountain from prohibited areas.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='rome'), (SELECT id FROM kb_categories WHERE name='laws'), 'Eating Near Monuments', 'Eating and drinking near the Colosseum, Trevi Fountain, and other monuments is restricted and can result in fines.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='rome'), (SELECT id FROM kb_categories WHERE name='laws'), 'Street Trading', 'Buying counterfeit goods from street vendors is illegal for both seller and buyer and can result in an on-the-spot fine.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='rome'), (SELECT id FROM kb_categories WHERE name='safety'), 'Unofficial Sellers', 'Avoid buying from unofficial sellers near attractions. Agreed prices can change and goods may be misrepresented.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='rome'), (SELECT id FROM kb_categories WHERE name='safety'), 'Scooter Traffic', 'Rome has heavy scooter traffic. Cross streets at pedestrian crossings and remain alert even when you have the right of way.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='rome'), (SELECT id FROM kb_categories WHERE name='safety'), 'Pickpocket Areas', 'The Colosseum, Vatican, and crowded bus routes are common areas for pickpocketing. Keep bags in front and phones out of back pockets.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='rome'), (SELECT id FROM kb_categories WHERE name='culture'), 'Coperto Charge', 'A coperto or cover charge for bread and table service is standard in Roman restaurants. It is not optional and will appear on the bill.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='rome'), (SELECT id FROM kb_categories WHERE name='culture'), 'Siesta Hours', 'Many smaller shops close between 1pm and 4pm for the afternoon rest period. Plan shopping and errands around this.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='rome'), (SELECT id FROM kb_categories WHERE name='culture'), 'Religious Observance', 'Rome is a deeply Catholic city. Respect religious services and avoid entering churches during Mass unless you are participating.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='rome'), (SELECT id FROM kb_categories WHERE name='transport'), 'Walking the Centre', 'Much of central Rome is best explored on foot. Cobblestones are uneven so wear comfortable shoes.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='rome'), (SELECT id FROM kb_categories WHERE name='transport'), 'Bus and Tram', 'Validate bus and tram tickets before boarding. Inspectors board regularly and fines for unvalidated tickets are significant.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='rome'), (SELECT id FROM kb_categories WHERE name='transport'), 'Taxi Rules', 'Only use licensed taxis from official ranks or apps. Agree on using the meter before departure to avoid overcharging.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='rome'), (SELECT id FROM kb_categories WHERE name='food'), 'Coffee Culture', 'Espresso is drunk standing at the bar. Ordering a cappuccino after noon marks you as a tourist as Italians only drink milky coffee in the morning.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='rome'), (SELECT id FROM kb_categories WHERE name='food'), 'Tourist Trap Restaurants', 'Avoid restaurants with laminated picture menus directly outside major attractions. Walk a street or two away for better value and quality.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='rome'), (SELECT id FROM kb_categories WHERE name='food'), 'Gelato Quality', 'Authentic gelato is stored in covered metal containers. Avoid shops displaying large colourful piles of gelato as these often contain artificial additives.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='rome'), (SELECT id FROM kb_categories WHERE name='timing'), 'Summer Heat and Crowds', 'July and August are very hot and crowded. Visit major sites early morning and take midday breaks in cooler spaces.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='rome'), (SELECT id FROM kb_categories WHERE name='timing'), 'Vatican Booking', 'Book Vatican Museum tickets online well in advance, especially in spring and summer, to avoid queues of several hours.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='rome'), (SELECT id FROM kb_categories WHERE name='weather'), 'Winter Mild', 'December to February is mild compared to northern Europe but can be rainy. Major attractions are less crowded in this period.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='rome'), (SELECT id FROM kb_categories WHERE name='weather'), 'Spring Ideal', 'April and May offer warm temperatures and lower crowds than summer, making them ideal months to visit.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='rome'), (SELECT id FROM kb_categories WHERE name='other'), 'Water Fountains', 'Rome has hundreds of free drinking water fountains called nasoni across the city. The water is fresh and safe to drink.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='rome'), (SELECT id FROM kb_categories WHERE name='other'), 'Trevi Fountain Coins', 'Throwing a coin in the Trevi Fountain is a popular tradition. Use the designated areas and avoid leaning over barriers.';


-- BARCELONA
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='barcelona'), (SELECT id FROM kb_categories WHERE name='etiquette'), 'Catalan Identity', 'Barcelona is in Catalonia and locals are proud of their distinct identity. Greeting in Catalan with Hola or Bon dia is appreciated.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='barcelona'), (SELECT id FROM kb_categories WHERE name='etiquette'), 'Dining Pace', 'Meals are social events. Do not rush and avoid asking for the bill immediately after finishing your food.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='barcelona'), (SELECT id FROM kb_categories WHERE name='etiquette'), 'Noise Levels', 'Barcelona has introduced noise ordinances in residential areas. Loud behaviour late at night can result in complaints or police attention.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='barcelona'), (SELECT id FROM kb_categories WHERE name='laws'), 'Beachwear Laws', 'Wearing swimwear away from the beach is illegal and can result in fines. Cover up when leaving beach areas.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='barcelona'), (SELECT id FROM kb_categories WHERE name='laws'), 'Alcohol in Public', 'Drinking alcohol in many public spaces is restricted. Check local signs and be aware that open containers can attract fines.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='barcelona'), (SELECT id FROM kb_categories WHERE name='laws'), 'Airbnb Regulations', 'Short-term rental regulations are strict in Barcelona. Ensure any accommodation you book is legally registered.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='barcelona'), (SELECT id FROM kb_categories WHERE name='safety'), 'Beach Theft', 'Never leave belongings unattended on the beach. Theft from unattended bags is extremely common at Barceloneta.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='barcelona'), (SELECT id FROM kb_categories WHERE name='safety'), 'Las Ramblas Pickpockets', 'Las Ramblas is beautiful but has a high concentration of pickpockets. Keep bags in front and phones secured.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='barcelona'), (SELECT id FROM kb_categories WHERE name='safety'), 'Scooter Theft', 'Bag snatching from scooters targeting pedestrians has been reported. Keep bags on the side away from the road.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='barcelona'), (SELECT id FROM kb_categories WHERE name='culture'), 'Siesta Rhythm', 'Smaller shops may close between 2pm and 5pm. Plan shopping and meals around this traditional rest period.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='barcelona'), (SELECT id FROM kb_categories WHERE name='culture'), 'FC Barcelona', 'Football is central to Barcelona culture. Attending a match at Camp Nou is a memorable experience but book well in advance.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='barcelona'), (SELECT id FROM kb_categories WHERE name='culture'), 'Gaudi Architecture', 'Sagrada Família and Park Güell require advance timed tickets. Queuing on the day can mean waiting several hours or being turned away.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='barcelona'), (SELECT id FROM kb_categories WHERE name='transport'), 'Metro Efficiency', 'The Barcelona Metro is clean and efficient. A T-Casual card offering ten journeys is good value for most visitors.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='barcelona'), (SELECT id FROM kb_categories WHERE name='transport'), 'Airport Bus', 'The Aerobus connects Barcelona airport to Plaça Catalunya in about 35 minutes and is the most convenient transfer option.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='barcelona'), (SELECT id FROM kb_categories WHERE name='transport'), 'Cycling Safety', 'Cycling infrastructure is growing but some lanes are shared with pedestrians. Follow signage and be cautious around the old town.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='barcelona'), (SELECT id FROM kb_categories WHERE name='food'), 'Late Dining', 'Locals eat dinner between 9pm and 11pm. Restaurants before 8pm cater mainly to tourists and menus may be limited.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='barcelona'), (SELECT id FROM kb_categories WHERE name='food'), 'Tapas Culture', 'Tapas are small sharing dishes. Order several for the table and share them rather than ordering one dish each.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='barcelona'), (SELECT id FROM kb_categories WHERE name='food'), 'Menu del Dia', 'The lunchtime menu del dia offers a starter, main, dessert, and drink at excellent value. It is the best way to eat well affordably.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='barcelona'), (SELECT id FROM kb_categories WHERE name='timing'), 'Summer Peak', 'July and August are the busiest and hottest months. Book everything in advance and expect crowded beaches and attractions.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='barcelona'), (SELECT id FROM kb_categories WHERE name='timing'), 'La Mercè Festival', 'The city''s biggest street festival takes place in late September with free concerts, fireworks, and human tower displays.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='barcelona'), (SELECT id FROM kb_categories WHERE name='weather'), 'Mediterranean Climate', 'Barcelona has warm summers and mild winters. Spring and autumn offer the most comfortable temperatures for sightseeing.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='barcelona'), (SELECT id FROM kb_categories WHERE name='weather'), 'Summer Heat', 'Temperatures regularly exceed 30 degrees in summer. Stay hydrated and plan heavy sightseeing for mornings and evenings.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='barcelona'), (SELECT id FROM kb_categories WHERE name='other'), 'Overtourism Awareness', 'Barcelona has experienced significant overtourism. Locals appreciate visitors who explore beyond the main tourist areas and support local businesses.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='barcelona'), (SELECT id FROM kb_categories WHERE name='other'), 'Language Sensitivity', 'While Spanish is widely spoken, using Catalan phrases is welcomed. Avoid assuming everyone prefers Spanish over Catalan.';


-- NEW YORK
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='newyork'), (SELECT id FROM kb_categories WHERE name='etiquette'), 'Tipping Culture', 'Tipping is essential in New York. Tip 18 to 20 percent at restaurants, one to two dollars per drink at bars, and one dollar per bag for porters.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='newyork'), (SELECT id FROM kb_categories WHERE name='etiquette'), 'Sidewalk Etiquette', 'Keep to the right on pavements and do not stop suddenly in the middle of a busy walkway. Move to the side if you need to check your phone.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='newyork'), (SELECT id FROM kb_categories WHERE name='etiquette'), 'Noise Levels', 'New York is a loud city but avoid playing music from speakers in public spaces and keep voices reasonable on public transport.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='newyork'), (SELECT id FROM kb_categories WHERE name='laws'), 'Jaywalking', 'Jaywalking is technically illegal but widely practised. Be cautious and always check for turning vehicles even when crossing with signals.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='newyork'), (SELECT id FROM kb_categories WHERE name='laws'), 'Open Container Laws', 'Drinking alcohol in open containers in public spaces is illegal in New York City and can result in a fine.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='newyork'), (SELECT id FROM kb_categories WHERE name='laws'), 'Smoking Restrictions', 'Smoking is banned in parks, beaches, pedestrian plazas, and outdoor dining areas. Violations carry fines.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='newyork'), (SELECT id FROM kb_categories WHERE name='safety'), 'Subway Safety', 'New York''s subway is generally safe but stay aware of your surroundings, especially late at night or on quieter platforms.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='newyork'), (SELECT id FROM kb_categories WHERE name='safety'), 'Phone Theft', 'Phone snatching is common on the subway. Avoid using your phone near open doors and keep it secured when not in use.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='newyork'), (SELECT id FROM kb_categories WHERE name='safety'), 'Times Square Scams', 'Be wary of costume characters in Times Square who approach tourists for photos and then demand payment aggressively.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='newyork'), (SELECT id FROM kb_categories WHERE name='culture'), 'Cultural Diversity', 'New York is one of the most culturally diverse cities in the world. Neighbourhoods like Flushing, Harlem, and Astoria offer rich multicultural experiences.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='newyork'), (SELECT id FROM kb_categories WHERE name='culture'), 'Broadway Etiquette', 'Arrive on time for Broadway shows. Late arrivals may not be seated until a break. Switch phones to silent before the performance begins.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='newyork'), (SELECT id FROM kb_categories WHERE name='culture'), 'Museum Mile', 'Fifth Avenue hosts some of the world''s great museums. Many offer pay-what-you-wish admission on certain evenings.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='newyork'), (SELECT id FROM kb_categories WHERE name='transport'), 'Subway Navigation', 'Download Citymapper or Google Maps for real-time subway updates. The OMNY contactless payment system works on all services.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='newyork'), (SELECT id FROM kb_categories WHERE name='transport'), 'Yellow Cabs', 'Hail yellow taxis from the pavement. The light on top indicates availability. Always ensure the meter is running from the start.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='newyork'), (SELECT id FROM kb_categories WHERE name='transport'), 'Airport Links', 'AirTrain connects JFK to the subway. For LaGuardia, use the M60 bus or a rideshare app. Allow extra time during rush hours.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='newyork'), (SELECT id FROM kb_categories WHERE name='food'), 'Diner Culture', 'Classic American diners are open around the clock and offer good value. Coffee refills are typically free.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='newyork'), (SELECT id FROM kb_categories WHERE name='food'), 'Food Diversity', 'New York offers cuisine from virtually every country. Explore neighbourhood restaurants in Queens and Brooklyn for the most authentic experiences.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='newyork'), (SELECT id FROM kb_categories WHERE name='food'), 'Bagel and Pizza Etiquette', 'Fold your pizza slice lengthwise to eat it the New York way. Bagels are eaten with a variety of fillings and are a city staple.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='newyork'), (SELECT id FROM kb_categories WHERE name='timing'), 'Rush Hour Congestion', 'Weekday mornings between 7am and 9am and evenings between 5pm and 7pm see peak crowds on roads and subways.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='newyork'), (SELECT id FROM kb_categories WHERE name='timing'), 'New Year Eve Crowds', 'Times Square on New Year''s Eve attracts millions of visitors. Arrive hours early and be prepared for restricted movement and cold temperatures.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='newyork'), (SELECT id FROM kb_categories WHERE name='weather'), 'Winter Cold', 'January and February can be bitterly cold with wind chill making temperatures feel far below freezing. Dress in warm layered clothing.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='newyork'), (SELECT id FROM kb_categories WHERE name='weather'), 'Summer Heat and Humidity', 'July and August are hot and humid. Central Park and the High Line are pleasant in the morning but intense in afternoon heat.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='newyork'), (SELECT id FROM kb_categories WHERE name='other'), 'Sales Tax', 'Sales tax is added at the register and not included in displayed prices. Expect around 8.875 percent added to most purchases.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='newyork'), (SELECT id FROM kb_categories WHERE name='other'), 'Free Attractions', 'Staten Island Ferry, the High Line, Brooklyn Bridge walk, and many museum evenings are free and excellent experiences.';


-- MARRAKECH
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='marrakech'), (SELECT id FROM kb_categories WHERE name='etiquette'), 'Market Haggling', 'Haggling is expected in the souks. Start at around 40 to 50 percent of the asking price and negotiate from there.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='marrakech'), (SELECT id FROM kb_categories WHERE name='etiquette'), 'Hospitality Customs', 'Accepting mint tea when offered by shopkeepers is a gesture of hospitality. You are not obliged to buy anything.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='marrakech'), (SELECT id FROM kb_categories WHERE name='etiquette'), 'Public Displays of Affection', 'Public displays of affection between couples are frowned upon and can attract unwanted attention or confrontation.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='marrakech'), (SELECT id FROM kb_categories WHERE name='laws'), 'Photography Permission', 'Always ask before photographing people, particularly in markets. Some individuals object or may expect payment.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='marrakech'), (SELECT id FROM kb_categories WHERE name='laws'), 'Ramadan Observance', 'During Ramadan, eating, drinking, and smoking in public during daylight hours is disrespectful and may be restricted. Be sensitive to this.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='marrakech'), (SELECT id FROM kb_categories WHERE name='laws'), 'Drug Laws', 'Morocco has strict anti-drug laws. Any involvement with drugs, even cannabis which is cultivated locally, can result in serious legal consequences.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='marrakech'), (SELECT id FROM kb_categories WHERE name='safety'), 'Unofficial Guides', 'Be cautious with unsolicited guiding offers in the medina. Agree on any price clearly before accepting assistance and only use recommended guides.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='marrakech'), (SELECT id FROM kb_categories WHERE name='safety'), 'Getting Lost in the Medina', 'The medina is a maze of narrow streets. Download an offline map before exploring and note key landmark locations.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='marrakech'), (SELECT id FROM kb_categories WHERE name='safety'), 'Food and Water Safety', 'Drink bottled or filtered water. Choose busy and reputable restaurants and be cautious with raw salads and uncooked food.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='marrakech'), (SELECT id FROM kb_categories WHERE name='culture'), 'Modest Dress', 'Dress modestly particularly in the medina and near mosques. Cover shoulders and knees as a mark of respect.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='marrakech'), (SELECT id FROM kb_categories WHERE name='culture'), 'Mosque Entry', 'Non-Muslims are generally not permitted to enter mosques in Morocco. Admire them from the outside respectfully.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='marrakech'), (SELECT id FROM kb_categories WHERE name='culture'), 'Jemaa el-Fna Square', 'The main square is most vibrant at dusk with food stalls, musicians, and performers. Be aware of individuals who approach tourists expecting payment for photos.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='marrakech'), (SELECT id FROM kb_categories WHERE name='transport'), 'Petit Taxis', 'Small orange taxis operate within the city. Insist on the meter being used and agree the route before departure.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='marrakech'), (SELECT id FROM kb_categories WHERE name='transport'), 'Calèche Carriages', 'Horse-drawn carriages are a traditional way to see the city. Agree a fixed price before the journey begins.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='marrakech'), (SELECT id FROM kb_categories WHERE name='transport'), 'Walking the Medina', 'The medina is best explored on foot but be alert to motorbikes navigating the narrow lanes without warning.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='marrakech'), (SELECT id FROM kb_categories WHERE name='food'), 'Tagine and Couscous', 'Traditional Moroccan cuisine includes slow-cooked tagines and Friday couscous. Many riads offer authentic home-cooked experiences.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='marrakech'), (SELECT id FROM kb_categories WHERE name='food'), 'Street Food Safety', 'Choose stalls with high turnover of food and customers. Jemaa el-Fna food stalls are generally safe but check cleanliness before ordering.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='marrakech'), (SELECT id FROM kb_categories WHERE name='food'), 'Alcohol Availability', 'Alcohol is available in licensed restaurants and hotels but is not sold in the medina. Morocco is a Muslim-majority country so be respectful.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='marrakech'), (SELECT id FROM kb_categories WHERE name='timing'), 'Spring and Autumn', 'March to May and September to November offer the most comfortable temperatures for exploring. Summer can be intensely hot.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='marrakech'), (SELECT id FROM kb_categories WHERE name='timing'), 'Ramadan Period', 'Visiting during Ramadan offers a unique cultural experience but be aware that some services and restaurants may have limited hours.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='marrakech'), (SELECT id FROM kb_categories WHERE name='weather'), 'Summer Extreme Heat', 'June to August sees temperatures regularly exceeding 40 degrees. Plan outdoor activities for early morning and evening only.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='marrakech'), (SELECT id FROM kb_categories WHERE name='weather'), 'Cool Evenings', 'Even in summer, evenings can become cool in Marrakech. Bring a light layer for outdoor dining after sunset.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='marrakech'), (SELECT id FROM kb_categories WHERE name='other'), 'Hammam Experience', 'Traditional hammam bathhouses are a cultural experience. Separate facilities exist for men and women. Bring your own toiletries or use those provided.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='marrakech'), (SELECT id FROM kb_categories WHERE name='other'), 'Bargaining Beyond Souks', 'Negotiating prices is common beyond the markets too, including with taxi drivers and for excursion tours. Polite persistence is respected.';


-- BANGKOK
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='bangkok'), (SELECT id FROM kb_categories WHERE name='etiquette'), 'Respect for Monarchy', 'The Thai royal family is deeply revered. Never make negative comments about the monarchy as this can be considered offensive and is legally serious.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='bangkok'), (SELECT id FROM kb_categories WHERE name='etiquette'), 'Temple Dress Code', 'Cover shoulders and knees when visiting temples. Many temples provide wraps at the entrance for visitors who are not dressed appropriately.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='bangkok'), (SELECT id FROM kb_categories WHERE name='etiquette'), 'Wai Greeting', 'The wai, pressing palms together and bowing slightly, is the traditional greeting. Return a wai if someone offers it to you as a sign of respect.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='bangkok'), (SELECT id FROM kb_categories WHERE name='laws'), 'Lese Majeste Laws', 'Thailand has strict lese-majeste laws protecting the royal family. Defamatory statements about the monarchy can result in imprisonment.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='bangkok'), (SELECT id FROM kb_categories WHERE name='laws'), 'Drug Penalties', 'Drug offences in Thailand carry severe penalties including lengthy imprisonment. Never carry or use drugs and be cautious of strangers offering substances.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='bangkok'), (SELECT id FROM kb_categories WHERE name='laws'), 'Buddha Image Rules', 'Posing disrespectfully with or near Buddha images is illegal and deeply offensive. Tattoos of Buddha figures can also create legal issues.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='bangkok'), (SELECT id FROM kb_categories WHERE name='safety'), 'Tuk-Tuk Scams', 'If a tuk-tuk driver tells you a major temple is closed, this is almost always a scam designed to take you to a gem shop. Verify independently.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='bangkok'), (SELECT id FROM kb_categories WHERE name='safety'), 'Gem Scams', 'Avoid offers to visit gem shops at special prices. This is one of Bangkok''s most persistent tourist scams resulting in overpriced purchases.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='bangkok'), (SELECT id FROM kb_categories WHERE name='safety'), 'Street Food Hygiene', 'Choose stalls with high customer turnover and freshly cooked food. Avoid pre-cooked dishes sitting for long periods in the heat.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='bangkok'), (SELECT id FROM kb_categories WHERE name='culture'), 'Songkran Festival', 'Songkran in April is Thailand''s new year water festival. Expect to get soaked in celebrations across the city.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='bangkok'), (SELECT id FROM kb_categories WHERE name='culture'), 'Spirit Houses', 'Small shrines outside buildings are spirit houses. Do not touch, move, or make jokes about them as they hold significant spiritual importance.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='bangkok'), (SELECT id FROM kb_categories WHERE name='culture'), 'Saving Face', 'Thai culture values harmony and avoiding public confrontation. Raising your voice or showing anger in public is considered very inappropriate.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='bangkok'), (SELECT id FROM kb_categories WHERE name='transport'), 'BTS Skytrain', 'The BTS Skytrain is the fastest way to navigate central Bangkok and avoids the notorious road traffic congestion.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='bangkok'), (SELECT id FROM kb_categories WHERE name='transport'), 'Chao Phraya River Boats', 'River express boats are an efficient and scenic way to travel between riverside attractions including the Grand Palace and Wat Arun.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='bangkok'), (SELECT id FROM kb_categories WHERE name='transport'), 'Meter Taxis', 'Always insist on using the meter in taxis. If a driver refuses, find another cab. Flat rate offers are almost always more expensive.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='bangkok'), (SELECT id FROM kb_categories WHERE name='food'), 'Street Food Culture', 'Bangkok''s street food is world-famous. Pad Thai, som tam, and mango sticky rice from street stalls are often better than restaurant versions.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='bangkok'), (SELECT id FROM kb_categories WHERE name='food'), 'Spice Levels', 'Thai food can be very spicy. When ordering, specify pet nit noi meaning a little spicy if you have a low tolerance.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='bangkok'), (SELECT id FROM kb_categories WHERE name='food'), 'Night Markets', 'Bangkok has excellent night markets including Chatuchak and Rot Fai. Visit in the evening when temperatures are cooler.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='bangkok'), (SELECT id FROM kb_categories WHERE name='timing'), 'Cool Season', 'November to February is the best time to visit with lower humidity and temperatures making sightseeing much more comfortable.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='bangkok'), (SELECT id FROM kb_categories WHERE name='timing'), 'Rainy Season', 'May to October brings monsoon rains, usually heavy afternoon downpours. Morning visits to attractions are recommended.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='bangkok'), (SELECT id FROM kb_categories WHERE name='weather'), 'Heat and Humidity', 'Bangkok is hot and humid year-round. Carry water at all times, use sunscreen, and take breaks in air-conditioned spaces.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='bangkok'), (SELECT id FROM kb_categories WHERE name='weather'), 'Air Pollution', 'Bangkok can experience poor air quality particularly in the dry season. Check AQI levels if you are sensitive and consider wearing a mask on heavily polluted days.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='bangkok'), (SELECT id FROM kb_categories WHERE name='other'), 'Nightlife Safety', 'Bangkok''s nightlife is vibrant but keep an eye on drinks, agree prices before ordering in some venues, and arrange transport home in advance.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='bangkok'), (SELECT id FROM kb_categories WHERE name='other'), 'Temple Footwear', 'Remove shoes before entering temple buildings. Wear shoes that are easy to slip on and off to make this more convenient.';


-- REYKJAVIK
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='reykjavik'), (SELECT id FROM kb_categories WHERE name='etiquette'), 'Egalitarian Culture', 'Iceland has a very egalitarian society. Titles and formality are less common and people are generally addressed by first name.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='reykjavik'), (SELECT id FROM kb_categories WHERE name='etiquette'), 'Geothermal Pool Rules', 'Showering thoroughly without swimwear before entering public pools is mandatory and enforced. This is a strict hygiene requirement.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='reykjavik'), (SELECT id FROM kb_categories WHERE name='etiquette'), 'Respect for Nature', 'Icelanders have a deep respect for their natural environment. Never walk off marked paths at natural sites and do not disturb wildlife.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='reykjavik'), (SELECT id FROM kb_categories WHERE name='laws'), 'Off-Road Driving', 'Driving off designated roads is strictly illegal in Iceland and causes irreversible damage to fragile vegetation and landscapes.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='reykjavik'), (SELECT id FROM kb_categories WHERE name='laws'), 'Camping Rules', 'Wild camping is only permitted in designated areas. Always use official campsites and follow all site rules regarding waste and noise.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='reykjavik'), (SELECT id FROM kb_categories WHERE name='laws'), 'Drone Regulations', 'Drone use is restricted in many areas of Iceland including near airports, nature reserves, and populated areas. Obtain permits before flying.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='reykjavik'), (SELECT id FROM kb_categories WHERE name='safety'), 'Weather Unpredictability', 'Icelandic weather can change extremely rapidly. Always check forecasts before outdoor trips and be prepared to change plans at short notice.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='reykjavik'), (SELECT id FROM kb_categories WHERE name='safety'), 'Glacier and Volcano Safety', 'Never walk on glaciers or near active volcanic areas without a certified guide. Conditions can be dangerous and rapidly changing.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='reykjavik'), (SELECT id FROM kb_categories WHERE name='safety'), 'Emergency Mountain Rescue', 'Register your hiking or outdoor plans with safetravel.is before venturing into remote areas. This assists rescue services if needed.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='reykjavik'), (SELECT id FROM kb_categories WHERE name='culture'), 'Northern Lights Etiquette', 'When viewing the northern lights with others, avoid using bright phone screens or torches which can affect others'' experience and photography.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='reykjavik'), (SELECT id FROM kb_categories WHERE name='culture'), 'Icelandic Sagas', 'Iceland has a rich literary tradition of medieval sagas. Visiting the Saga Museum gives context to the country''s history and culture.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='reykjavik'), (SELECT id FROM kb_categories WHERE name='culture'), 'Swimming Pool Culture', 'Local geothermal pools are social hubs for Icelanders. Visit a community pool for an authentic local experience away from tourist crowds.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='reykjavik'), (SELECT id FROM kb_categories WHERE name='transport'), 'Car Rental Essentials', 'A four-wheel-drive vehicle is strongly recommended for exploring outside Reykjavik, particularly on F-roads in the highlands.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='reykjavik'), (SELECT id FROM kb_categories WHERE name='transport'), 'Road Conditions', 'Check road.is before every journey. Roads can close suddenly due to ice, snow, or volcanic activity even in summer.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='reykjavik'), (SELECT id FROM kb_categories WHERE name='transport'), 'City Walkability', 'Reykjavik city centre is very walkable and most attractions are within comfortable walking distance of each other.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='reykjavik'), (SELECT id FROM kb_categories WHERE name='food'), 'Skyr and Local Foods', 'Skyr is a thick Icelandic dairy product similar to yoghurt. Local lamb, Arctic char, and fermented shark are traditional specialities.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='reykjavik'), (SELECT id FROM kb_categories WHERE name='food'), 'Cost of Dining', 'Iceland is expensive. Self-catering and visiting local bakeries for lunch offers significant savings compared to restaurant dining.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='reykjavik'), (SELECT id FROM kb_categories WHERE name='food'), 'Hot Dogs', 'Reykjavik''s iconic hot dog stand Bæjarins Beztu Pylsur is a beloved local institution. The classic order is with everything including remoulade.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='reykjavik'), (SELECT id FROM kb_categories WHERE name='timing'), 'Northern Lights Season', 'The northern lights are visible from September to March when skies are dark. Clear nights away from city lights offer the best sightings.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='reykjavik'), (SELECT id FROM kb_categories WHERE name='timing'), 'Midnight Sun', 'In June and July the sun barely sets, creating the midnight sun phenomenon. Bring a sleep mask if light sensitivity affects your sleep.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='reykjavik'), (SELECT id FROM kb_categories WHERE name='weather'), 'Layering is Essential', 'Weather changes extremely rapidly in Iceland. Always dress in layers and carry waterproof and windproof outer layers even in summer.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='reykjavik'), (SELECT id FROM kb_categories WHERE name='weather'), 'Wind Chill Factor', 'Wind chill can make temperatures feel significantly colder than readings suggest. Check the feels-like temperature before outdoor activities.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='reykjavik'), (SELECT id FROM kb_categories WHERE name='other'), 'Environmental Responsibility', 'Iceland''s landscapes are fragile. Stick to marked paths, take all litter with you, and report any damage you witness.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='reykjavik'), (SELECT id FROM kb_categories WHERE name='other'), 'High Costs', 'Iceland is one of the most expensive destinations in the world. Budget carefully and research costs for activities, food, and transport in advance.';


-- SIEM REAP
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='siemreap'), (SELECT id FROM kb_categories WHERE name='etiquette'), 'Temple Dress Code', 'Cover shoulders and knees at all Angkor temple sites. Entry can and will be refused for those not dressed appropriately.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='siemreap'), (SELECT id FROM kb_categories WHERE name='etiquette'), 'Greeting Monks', 'Do not initiate physical contact with monks. Women in particular should avoid touching or handing items directly to monks.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='siemreap'), (SELECT id FROM kb_categories WHERE name='etiquette'), 'Removing Footwear', 'Remove shoes before entering temple inner sanctuaries and before entering local homes when invited.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='siemreap'), (SELECT id FROM kb_categories WHERE name='laws'), 'Angkor Temple Conduct', 'Climbing on temple structures is prohibited and can result in fines and expulsion from the site. Respect all preservation barriers.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='siemreap'), (SELECT id FROM kb_categories WHERE name='laws'), 'Drone Regulations', 'Flying drones over the Angkor Archaeological Park requires a special permit. Unauthorised drone use results in fines and confiscation.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='siemreap'), (SELECT id FROM kb_categories WHERE name='laws'), 'Currency Rules', 'US dollars are widely accepted alongside Cambodian riel. Exchanging money at official banks or licensed exchanges is recommended.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='siemreap'), (SELECT id FROM kb_categories WHERE name='safety'), 'Tuk-Tuk Agreements', 'Agree fares with tuk-tuk drivers before departure. Negotiate a full-day rate for visiting multiple temples as this is better value.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='siemreap'), (SELECT id FROM kb_categories WHERE name='safety'), 'Landmine Awareness', 'Some rural areas of Cambodia still have unexploded ordnance. Stick to well-travelled roads and paths outside of tourist zones.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='siemreap'), (SELECT id FROM kb_categories WHERE name='safety'), 'Medical Facilities', 'Medical facilities in Siem Reap are limited. Ensure you have comprehensive travel insurance and carry any essential medications with you.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='siemreap'), (SELECT id FROM kb_categories WHERE name='culture'), 'Angkor Pass', 'Purchase your Angkor Archaeological Park pass only from the official ticket centre. Never buy from unofficial sellers.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='siemreap'), (SELECT id FROM kb_categories WHERE name='culture'), 'Khmer New Year', 'Khmer New Year in April is Cambodia''s most important festival. Temples and businesses may have altered opening hours during this period.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='siemreap'), (SELECT id FROM kb_categories WHERE name='culture'), 'Smiling Culture', 'Cambodians are known for their warmth and smiles. A smile goes a long way in building positive interactions with locals.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='siemreap'), (SELECT id FROM kb_categories WHERE name='transport'), 'Temple Circuit Options', 'The small circuit covering Angkor Wat, Bayon, and Ta Prohm takes a full day. The grand circuit requires two days minimum.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='siemreap'), (SELECT id FROM kb_categories WHERE name='transport'), 'Electric Tuk-Tuks', 'Electric tuk-tuks are a quieter and more eco-friendly way to visit the temples and are available from the main tourist areas.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='siemreap'), (SELECT id FROM kb_categories WHERE name='transport'), 'Bicycle Rental', 'Cycling between the temples of the small circuit is popular and gives more flexibility but the distances are significant in the heat.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='siemreap'), (SELECT id FROM kb_categories WHERE name='food'), 'Khmer Cuisine', 'Try amok, a coconut-based fish curry, and lok lak, a pepper beef stir fry, as classic Khmer dishes.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='siemreap'), (SELECT id FROM kb_categories WHERE name='food'), 'Pub Street Dining', 'Pub Street offers a wide range of food options at tourist-friendly prices. Venture further for more authentic local eating experiences.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='siemreap'), (SELECT id FROM kb_categories WHERE name='food'), 'Water Safety', 'Drink only bottled or filtered water. Avoid ice in drinks unless you are certain it was made from purified water.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='siemreap'), (SELECT id FROM kb_categories WHERE name='timing'), 'Sunrise at Angkor Wat', 'Sunrise over Angkor Wat is iconic but the main reflection pool is crowded. Arrive by 5am and consider alternative viewpoints.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='siemreap'), (SELECT id FROM kb_categories WHERE name='timing'), 'Dry Season', 'November to April is the dry season and the best time to visit. Temple paths are dry and accessible and skies are clear.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='siemreap'), (SELECT id FROM kb_categories WHERE name='weather'), 'Monsoon Season', 'May to October brings heavy rains. The temples are greener and less crowded but paths can become muddy and some areas may flood.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='siemreap'), (SELECT id FROM kb_categories WHERE name='weather'), 'Heat Management', 'Temperatures exceed 35 degrees in the dry season. Start temple visits at dawn, rest midday, and carry at least two litres of water.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='siemreap'), (SELECT id FROM kb_categories WHERE name='other'), 'Responsible Tourism', 'Support locally owned guesthouses, restaurants, and tour operators to ensure your spending benefits the local community directly.';
INSERT INTO knowledge_base (destination_id, category_id, title, content) SELECT (SELECT id FROM destinations WHERE slug='siemreap'), (SELECT id FROM kb_categories WHERE name='other'), 'Child Welfare', 'Do not give money, sweets, or gifts directly to children as this encourages begging and can be harmful. Support reputable local charities instead.';